# Exclude Groups Test Configuration  
# Use this to test filtering out unwanted groups (like AD imported groups)

okta:
  domain: "your-org.okta.com"  # Replace with your actual Okta domain
  api_token: "${OKTA_API_TOKEN}"

braintrust_orgs:
  carlos:
    api_key: "${BRAINTRUST_CARLOS_API_KEY}"
    url: "https://api.braintrust.dev"

sync_modes:
  declarative:
    enabled: true

sync_rules:
  users:
    enabled: true
    mappings:
      # Only active users (should exclude carlos+inactive)
      - okta_filter: 'status eq "ACTIVE"'
        braintrust_orgs: ["carlos"]
        enabled: true

  groups:
    enabled: true
    mappings:
      # Exclude the AD-Imported-Group (should find 4 groups instead of 5)
      - okta_group_filter: 'type eq "OKTA_GROUP" and profile.name ne "AD-Imported-Group"'
        braintrust_orgs: ["carlos"]
        enabled: true