# Test configuration for okta-braintrust-sync
# This config is designed to work with the Terraform test data setup

okta:
  domain: "your-org.okta.com"  # Replace with your Okta domain
  api_token: "${OKTA_API_TOKEN}"

braintrust_orgs:
  test:
    api_key: "${BRAINTRUST_TEST_API_KEY}"  # You'll create this in Braintrust
    url: "https://api.braintrust.dev"

# Only declarative mode is currently implemented
sync_modes:
  declarative:
    enabled: true

sync_rules:
  users:
    enabled: true
    mappings:
      # Start with all active users (should find 5 users from Terraform setup)
      - okta_filter: 'status eq "ACTIVE"'
        braintrust_orgs: ["test"]
        enabled: true

  groups:
    enabled: true
    mappings:
      # Start with all OKTA_GROUP types (should find 5 groups from Terraform setup)
      - okta_group_filter: 'type eq "OKTA_GROUP"'
        braintrust_orgs: ["test"]
        enabled: true

# You can uncomment these for more advanced testing after basic sync works:
#
# # Filter by department only
# sync_rules:
#   users:
#     enabled: true
#     mappings:
#       - okta_filter: 'status eq "ACTIVE" and profile.department eq "ML Engineering"'
#         braintrust_orgs: ["test"]
#         enabled: true
#
# # Filter specific groups
# sync_rules:
#   groups:
#     enabled: true
#     mappings:
#       - okta_group_filter: 'type eq "OKTA_GROUP" and profile.name eq "ML-Engineering"'
#         braintrust_orgs: ["test"]
#         enabled: true
#
# # Exclude AD groups
# sync_rules:
#   groups:
#     enabled: true
#     mappings:
#       - okta_group_filter: 'type eq "OKTA_GROUP" and profile.name ne "AD-Imported-Group"'
#         braintrust_orgs: ["test"]
#         enabled: true