# Basic Test Configuration
# Use this first to test that everything works with the Terraform test data

okta:
  domain: "your-org.okta.com"  # Replace with your actual Okta domain
  api_token: "${OKTA_API_TOKEN}"

braintrust_orgs:
  test:
    api_key: "${BRAINTRUST_TEST_API_KEY}"
    url: "https://api.braintrust.dev"

sync_modes:
  declarative:
    enabled: true

sync_rules:
  users:
    enabled: true
    mappings:
      # Should find 5 active users from Terraform setup
      - okta_filter: 'status eq "ACTIVE"'
        braintrust_orgs: ["test"]
        enabled: true

  groups:
    enabled: true
    mappings:
      # Should find 5 groups from Terraform setup
      - okta_group_filter: 'type eq "OKTA_GROUP"'
        braintrust_orgs: ["test"]
        enabled: true