# Filtered Test Configuration
# Use this after basic-test.yaml works to test filtering capabilities

okta:
  domain: "your-org.okta.com"  # Replace with your actual Okta domain
  api_token: "${OKTA_API_TOKEN}"

braintrust_orgs:
  test:
    api_key: "${BRAINTRUST_TEST_API_KEY}"
    url: "https://api.braintrust.dev"

sync_modes:
  declarative:
    enabled: true

sync_rules:
  users:
    enabled: true
    mappings:
      # Should find 2 ML Engineers (carlos+ml1, carlos+ml2)
      - okta_filter: 'status eq "ACTIVE" and profile.department eq "ML Engineering"'
        braintrust_orgs: ["test"]
        enabled: true

  groups:
    enabled: true
    mappings:
      # Should find just the ML-Engineering group
      - okta_group_filter: 'type eq "OKTA_GROUP" and profile.name eq "ML-Engineering"'
        braintrust_orgs: ["test"]
        enabled: true