# Multi-Team Test Configuration
# Use this to test syncing different teams to different environments

okta:
  domain: "your-org.okta.com"  # Replace with your actual Okta domain
  api_token: "${OKTA_API_TOKEN}"

braintrust_orgs:
  dev:
    api_key: "${BRAINTRUST_DEV_API_KEY}"
    url: "https://api.braintrust.dev"
  prod:
    api_key: "${BRAINTRUST_PROD_API_KEY}"
    url: "https://api.braintrust.dev"

sync_modes:
  declarative:
    enabled: true

sync_rules:
  users:
    enabled: true
    mappings:
      # All active users go to dev
      - okta_filter: 'status eq "ACTIVE"'
        braintrust_orgs: ["dev"]
        enabled: true
      
      # Only ML Engineers and Platform Admin go to prod
      - okta_filter: 'status eq "ACTIVE" and (profile.department eq "ML Engineering" or profile.department eq "Platform")'
        braintrust_orgs: ["prod"]
        enabled: true

  groups:
    enabled: true
    mappings:
      # All groups go to dev
      - okta_group_filter: 'type eq "OKTA_GROUP" and profile.name ne "AD-Imported-Group"'
        braintrust_orgs: ["dev"]
        enabled: true
      
      # Only ML and Platform Admin groups go to prod
      - okta_group_filter: 'type eq "OKTA_GROUP" and (profile.name eq "ML-Engineering" or profile.name eq "GenAI-Platform-Admins")'
        braintrust_orgs: ["prod"]
        enabled: true