# Group Assignment Example
# Shows how to assign users to groups based on Okta data

# Okta API configuration  
okta:
  domain: "${OKTA_ORG_NAME}.okta.com"
  api_token: "${OKTA_API_TOKEN}"
  rate_limit_per_minute: 600
  timeout_seconds: 30

# Braintrust organizations
braintrust_orgs:
  production:
    api_key: "${BRAINTRUST_PROD_API_KEY}"
    url: "https://api.braintrust.dev"
    timeout_seconds: 30
    rate_limit_per_minute: 300
  
  development:
    api_key: "${BRAINTRUST_DEV_API_KEY}"
    url: "https://api.braintrust.dev"
    timeout_seconds: 30
    rate_limit_per_minute: 300

# Basic user and group sync
sync_rules:
  users:
    enabled: true
    mappings:
      - okta_filter: 'status eq "ACTIVE"'
        braintrust_orgs: ["production", "development"]
        enabled: true
    
    identity_mapping:
      strategy: "email"
      case_sensitive: false
    
    create_missing: true
    update_existing: true
    sync_profile_fields: ["firstName", "lastName", "email", "login"]

  # Group sync disabled - groups created via group assignment
  groups:
    enabled: false

# Group assignment strategies
group_assignment:
  global_config:
    # Strategy 1: Direct Okta group mapping
    strategy: "okta_groups"
    
    okta_group_mappings:
      - okta_group_name: "BT-Engineering"
        braintrust_group_name: "Engineering"
      - okta_group_name: "BT-DataScience"
        braintrust_group_name: "DataScience"
      - okta_group_name: "BT-ProductManagement"
        braintrust_group_name: "ProductManagement"
      - okta_group_name: "BT-Leadership"
        braintrust_group_name: "Leadership"
    
    sync_group_names: true
    auto_create_groups: true
    default_groups: ["AllEmployees"]
    max_groups_per_user: 10

# Sync mode
sync_modes:
  declarative:
    enabled: true
    schedule: "0 */4 * * *"  # Every 4 hours
    max_concurrent_orgs: 2
  
  realtime:
    enabled: false

# Sync options
sync_options:
  dry_run: false
  batch_size: 50
  max_retries: 3
  retry_delay_seconds: 1.0
  remove_extra: false
  continue_on_error: true

# Audit logging
audit:
  enabled: true
  log_level: "INFO"
  log_format: "json"
  retention_days: 30